### ISSUE TITLE
RFI: use tarteaucitron pro

### ISSUE THREAD

**Issue by emsuiko** [la-haute-societe/craft-tarteaucitron#2]
Hey there,

how would I use the tarteaucitron.js pro version with this plugin?
As far as I can see it uses the open source one (which is great btw!).
If I'd like to localize the banner for instance I need the pro version of the javascript, right?

Thanks & regards

**Comment by nstcactus** [comment]
Hi,

Currently there is no way of using tarteaucitron.js pro with our plugin.

As far as I understand tarteaucitron.js pro, supporting the pro version would make little sense since it includes all the features of our plugin.

To customize the translations, using tarteaucitron.js pro surely makes it easier. You can still achieve it with the free version but it would require some serious arm twisting. This isn't supported by our plugin either but we'll consider it.

**Comment by emsuiko** [comment]
Thank you for your quick response!

Do I understand it right, that it is not possible at the moment to render the cookie banner in another language than English?

**Comment by nstcactus** [comment]
The cookie bar is already localized (here are the [supported languages](https://github.com/AmauriC/tarteaucitron.js/tree/master/lang)), even with the free version. The pro version let's you customize translations.

The language is determined using the HTTP Accept-Language header but you can force a language by defining a `tarteaucitronForceLanguage` JS variable before loading tarteaucitron.

Our Craft plugin does not yet support forcing a language but that's definitely one of the next feature we'll implement.

**Comment by emsuiko** [comment]
Ah, I see! Thank you! :)

And I realize I should've probably used a different/more fitting issue summary. Sorry for that.
